apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
#  Name: bluecompute-customer-pipeline-run
  generateName: bluecompute-inventory-pr-
spec:
  pipelineRef:
    name: bluecompute-build-and-deploy-pipeline-inventory
  resources:
    - name: git-source-inventory
      resourceRef:
        name: git-source-inventory
    - name: docker-image
      resourceRef:
        name: docker-image
  params:
    - name: pathToYamlFile
      value: "k8s/deployment.yaml"
    - name: image-name
      value: us.icr.io/jhovany/bluecompute-inventory
    - name: image-tag
      value: "0.6.1"
  serviceAccount: pipeline-account
  timeout: "1h0m0s"
